name: stm-dashboard 
channels:
  - conda-forge
  - pyviz
dependencies:
  - dask[complete]
  - dask-labextension
  - geopandas
  - geoviews
  - holoviews
  - hvplot
  - jupyterlab>=3
  - jupyterlab-git
  - jupyter_bokeh
  - panel
  - pip
  - spatialpandas
  - xarray
  - zarr
  - pip:
    - git+https://github.com/MotionbyLearning/stmtools
